pool:
  vmImage: 'windows-latest'

variables:
  yarnCacheFolder: $(Pipeline.Workspace)/.yarn
  majorVersion: '0'
  minorVersion: '1'

name: $(majorVersion).$(minorVersion)$(Rev:.r)

steps:
- checkout: self
  persistCredentials: false

- task: NodeTool@0
  inputs:
    versionSpec: '12.18.x'
  displayName: 'install Node.js'

- script: yarn config set cache-folder $(yarnCacheFolder)
  displayName: 'yarn config set cache-folder'

- task: Cache@2
  inputs:
    key: 'version1 | yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       version1 | yarn | "$(Agent.OS)"
       version1 | yarn
    path: $(yarnCacheFolder)
  displayName: 'restore Yarn packages from cache'

- script: yarn config set version-git-tag false
  displayName: 'yarn config set version-git-tag false'

- script: yarn install --frozen-lockfile
  displayName: 'yarn install --frozen-lockfile'